services:
  docker-tomcat:
    image: library/tomcat:9
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/logs:/usr/local/tomcat/logs
  docker-mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=abtests'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=myuser'
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    restart: always


